### ISSUE TITLE
关于Js划线后不能显示

### ISSUE THREAD

**Issue by Sherrylone** [jiyinqin/NeuralView#1]
实现通过按钮添加层数，同时添加神经元之间连线，连线部分通过make_line()做，实现每一次通过添加按钮，删除按钮，都可以添加或删除元素，同时调用make_line进行画线。经过devtool检查，make_line函数的功能已经实现，但是通过Js添加的dom元素并未在<g>标签中显示。需要解决这个问题

**Comment by Agrimonia** [comment]
命名空间了解一下，有关 SVG 的教程都会讲的

**Comment by Agrimonia** [comment]
你想用 Javascript 操作 SVG 元素不能像 HTML 那样创建元素之间添加到 DOM，要用 createElentNS()
